CREATE TABLE CONTAS(
  ID NUMBER GENERATED ALWAYS AS IDENTITY,
  NROCONTA VARCHAR2(200),
  ID_CLIENTE NUMBER,
  SALDO NUMBER(19,5),
  DTACREATED TIMESTAMP,
  DTAUPDATE TIMESTAMP,

  PRIMARY KEY(ID),
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID)
);
