SELECT * FROM CURSO
WHERE NROMAXALUNO>30
AND EAD = 1;


SELECT * FROM PROFESSOR
WHERE NACIONALIDADE = 'America do Sul';


SELECT * FROM ESTUDANTE
WHERE UPPER(NOME) LIKE 'J%'

SELECT * FROM ESTUDANTE
WHERE MEDIAGERAL>7
ORDER BY MEDIAGERAL DESC;


SELECT E.* FROM MATRICULA M
INNER JOIN ESTUDANTE E
      ON E.IDESTUDANTE = M.IDESTUDANTE
INNER JOIN CURSO C
      ON C.IDCURSO = M.IDCURSO
AND C.EAD = 1
-- 2 FORMA
SELECT E.* FROM MATRICULA M, ESTUDANTE E, CURSO C
WHERE E.IDESTUDANTE = M.IDESTUDANTE
AND C.IDCURSO = M.IDCURSO
AND C.EAD = 1
