CREATE TABLE TABELAPRECO(
                            idTabelaPreco NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                            descricao VARCHAR2(100),
                            VlrLocacao NUMBER(8,2),

                            PRIMARY KEY(idTabelaPreco)
)
/
CREATE TABLE FILME(
                      idFilme NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                      titulo VARCHAR2(100),
                      classificacao NUMBER(19,2),
                      idTabelaPreco  NUMBER(19),

                      PRIMARY KEY (idFilme),
                      FOREIGN KEY (idTabelaPreco) REFERENCES TABELAPRECO (idTabelaPreco)
)
/
CREATE TABLE CATEGORIA(
                          idCategoria NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                          descricao VARCHAR2(100),

                          PRIMARY KEY(idCategoria)
)
/
CREATE TABLE FILMECATEGORIA(
                               idFilme NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                               idCategoria NUMBER(8),

                               PRIMARY KEY(idFilme, idCategoria),
                               FOREIGN KEY (idFilme) REFERENCES FILME (idFilme),
                               FOREIGN KEY (idCategoria) REFERENCES CATEGORIA (idCategoria)
)
/
CREATE TABLE ATOR(
                     idAtor NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                     nome VARCHAR2(1000),
                     dtaNacto DATE,

                     PRIMARY KEY (idAtor)
)
/
CREATE TABLE ELENCO(
                       idElenco NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                       idFilme NUMBER(8),
                       idAtor NUMBER(8),
                       nomePersonagem VARCHAR2(1000),

                       PRIMARY KEY(idElenco),
                       FOREIGN KEY (idAtor) REFERENCES ATOR (idAtor),
                       FOREIGN KEY (idFilme) REFERENCES FILME (idFilme)
)
/
CREATE TABLE CLIENTE(
                        idCliente NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                        nome VARCHAR2(1000),
                        sobrenome VARCHAR2(1000),
                        telefone VARCHAR2(15),
                        logradouro VARCHAR2(1000),
                        nroLogradouro VARCHAR2(10),
                        complemento VARCHAR(100),
                        bairro VARCHAR(200),
                        cidade VARCHAR(100),
                        uf char(2),

                        PRIMARY KEY(idCliente)
)
/
CREATE TABLE LOCACAO(
                        idLocacao NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                        idCliente NUMBER(8),
                        idFilme NUMBER(8),
                        dtaLocacao DATE,
                        dtaDevolucao DATE,

                        PRIMARY KEY(idLocacao),
                        FOREIGN KEY (idCliente) REFERENCES CLIENTE (idCliente),
                        FOREIGN KEY (idFilme) REFERENCES FILME (idFilme)
)